version: '3'

services:
  backend:
    build: ./docker/python
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./backend/:/app/

  frontend:
    build: ./docker/apache
    ports:
      - 8000:80
    volumes:
      - ./frontend/public-html/:/usr/local/apache2/htdocs/

  php:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - ./frontend/public-html/:/var/www/html/

  db:
    build: ./docker/db
    ports:
      - 3306:3306